version: '3.7'
services:
  ppt:
    container_name: ppm
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-ppm
    restart: always
    network_mode: "host"
    volumes:
      - ~/as-15-8-ppm/logs:/log
      - ~/as-15-8-ppm/config:/config
    environment:
      PROFILE: prod
      GATEWAY_URI: http://10.97.220.145:15880
      TZ: "Europe/Moscow"
    ports:
      - "15803:15803"