version: '3.7'
services:
  birt:
    container_name: report_generator
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-birt:latest
    network_mode: "host"
    restart: always
    environment:
      PROFILE: prod
      GATEWAY_URI: http://10.97.220.134:15880
      TZ: "Europe/Moscow"
    ports:
      - "15813:15813"
    volumes:
      - ~/as-15-8-ppo/birt/logs:/log
      - ~/as-15-8-ppo/birt/config:/config
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  rep-scheduler:
    container_name: report_scheduler
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-rep-scheduler:latest
    restart: always
    network_mode: "host"
    environment:
      PROFILE: prod
      GATEWAY_URI: http://10.97.220.134:15880
      TZ: "Europe/Moscow"
    ports:
      - "15812:15812"
    volumes:
      - ~/as-15-8-ppo/rep-scheduler/logs:/log
      - ~/as-15-8-ppo/rep-scheduler/config:/config
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  rep-viewer:
    container_name: report_viewer
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-rep-viewer:latest
    restart: always
    environment:
      PROFILE: prod
      GATEWAY_URI: http://10.97.220.134:15880
      TZ: "Europe/Moscow"
    ports:
      - "15814:15814"
    volumes:
      - ~/as-15-8-ppo/rep-viewer/config:/config
    extra_hosts:
      - "asdb:10.97.220.144"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    networks:
      net:
  rep-gate:
    container_name: report_gate
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-rep-gate:latest
    restart: always
    ports:
      - "8079:80"
    environment:
      GATEWAY_URI: http://10.97.220.134:15880
      PROFILE: "prod"
      BASIC_AUTH: "YmlydC12aWV3ZXI6MXEwcDJ3OW8="
      CLIENTID: "birt-viewer"
      CLIENT_SECRET: "1q0p2w9o"
      TZ: "Europe/Moscow"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    volumes:
      - ~/as-15-8-ppo/rep-gate/config:/config
    networks:
      net:
  filebeat:
    container_name: filebeat_ppo
    image: dcr.ec-leasing.ru/as-15-8/elk/filebeat:7.2.0
    restart: on-failure
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/data:/usr/share/filebeat/data:rw
    command: filebeat -e -strict.perms=false
    user: root
networks:
  net: