version: '3.7'
networks:
  as-15-8-net:
services:
  birt:
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-birt:latest
    networks:
      - as-15-8-net
    restart: always
    environment:
#      PROFILE: test
      GATEWAY_URI: http://192.168.5.50:15880
      TZ: "Europe/Moscow"
    ports:
      - "15813:15813"
    volumes:
      - ~/as-15-8-ppo/birt/logs:/log
      - ~/as-15-8-ppo/config:/config
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  rep-scheduler:
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-rep-scheduler:latest
    restart: always
    networks:
      - as-15-8-net
    environment:
#      PROFILE: test
      GATEWAY_URI: http://192.168.5.50:15880
      TZ: "Europe/Moscow"
    ports:
      - "15812:15812"
    volumes:
      - ~/as-15-8-ppo/rep-scheduler/logs:/log
      - ~/as-15-8-ppo/config:/config
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  filebeat:
    image: harbor.ec-leasing.ru/as_15_8/elk/filebeat:7.2.0
    restart: on-failure
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/data:/usr/share/filebeat/data:rw
    command: filebeat -e -strict.perms=false
    user: root