version: '3.7'
services:
  birt:
    container_name: report_generator
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-birt:latest
    network_mode: "host"
    restart: always
    environment:
      PROFILE: test
      GATEWAY_URI: http://10.97.220.134:15880
      TZ: "Europe/Moscow"
    ports:
      - "15813:15813"
    volumes:
      - ~/as-15-8-ppo/birt/logs:/log
      - ~/as-15-8-ppo/birt/config:/config
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  rep-scheduler:
    container_name: report_scheduler
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-rep-scheduler:latest
    restart: always
    network_mode: "host"
    environment:
      PROFILE: test
      GATEWAY_URI: http://10.97.220.134:15880
      TZ: "Europe/Moscow"
    ports:
      - "15812:15812"
    volumes:
      - ~/as-15-8-ppo/rep-scheduler/logs:/log
      - ~/as-15-8-ppo/rep-scheduler/config:/config
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  filebeat:
    image: dcr.ec-leasing.ru/as-15-8/elk/filebeat:7.2.0
    restart: on-failure
    volumes:
      - ./filebeat/filebeat.prod.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/data:/usr/share/filebeat/data:rw
    command: filebeat -e -strict.perms=false
    user: root