version: '3.7'
services:
  rep-viewer:
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-rep-viewer:latest
    network_mode: "host"
    restart: always
    environment:
      TZ: "Europe/Moscow"
    ports:
      - "8078:8080"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  rep-gate:
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-rep-gate:latest
    network_mode: "host"
    restart: always
    environment:
      TZ: "Europe/Moscow"
    ports:
      - "8079:80"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
