subsystem: PPO
server:
  port: 15812
gateway.url: ${GATEWAY_URI:http://localhost:15880}
eureka:
  client:
    serviceUrl:
      defaultZone: ${gateway.url}/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring:
  application.name: report_scheduler
  liquibase:
    enabled: true
    change-log: classpath:data/db.changelog.master.xml
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    max-active: 5
    username: as_user
    password: as_user
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
app:
  birt.url: 'http://localhost:15813/reglament/'
  schedule: '5 0 * * * ?'

---

logging:
  config:
  level:
    root: info
    model: debug
    repositories: debug
    controllers: debug
    common: debug
    schedule: debug
    org.springframework.data: debug
    org.springframework.web: debug
    org.springframework.http: debug
eureka:
  client:
    enabled: false
spring:
  profiles: dev_asin
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
  liquibase:
    enabled: false
  cloud:
    bus.trace.enabled: false
    config:
      bus:
        enabled: false
    stream:
      bindings:
        springCloudBusInput:
          group: config_server
      kafka.binder:
        brokers:
app:
  schedule: '*/10 * * * * ?'


---

logging:
  config:
  level:
    root: info
    model: info
    repositories: info
    controllers: info
    common: info
    schedule: info
    org.springframework.data: info
    org.springframework.web: info
    org.springframework.http: info
eureka:
  client:
    enabled: false
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
  liquibase:
    enabled: false
  cloud:
    bus.trace.enabled: false
    config:
      bus:
        enabled: false
    stream:
      bindings:
        springCloudBusInput:
          group: config_server
      kafka.binder:
        brokers:
app:
  birt.url: 'http://birt:15813/reglament/'
  schedule: '*/10 * * * * ?'



