subsystem: PPO
server:
  port: 15812
logging:
  config: config/logback-spring.xml
gateway.url: ${GATEWAY_URI:http://localhost:15880}
eureka:
  client:
    serviceUrl:
      defaultZone: ${gateway.url}/eureka
    oauth2:
      clientId: report_scheduler
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${gateway.url}/security/oauth/token
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring:
  application.name: report_scheduler
  main.allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:data/db.changelog.master.xml
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    max-active: 5
    username: as_user
    password: as_user
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
app:
  birt.url: ${gateway.url}/report_generator
  schedule: '5 0 * * * ?'
  sql:
    refresh-dm: select dm.update_at()
    # Вызывается перед запуском всех отчетов, без параметра
    before-all:
    # Вызывается перед запуском каждлго отчета, параметр -- rep_id из таблицы
    before-each: select dm.update_reports_data(?)
security:
  oauth2:
    resource:
      tokenInfoUri: ${gateway.url}/security/oauth/check_token
    client:
      clientId: report_scheduler
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${gateway.url}/security/oauth/token

---

logging:
  config:
  level:
    root: info
    model: debug
    repositories: debug
    controllers: debug
    common: debug
    schedule: debug
    org.springframework.data: debug
    org.springframework.web: debug
    org.springframework.http: debug
spring:
  profiles: dev_asin
  profiles.include: local_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
  liquibase:
    enabled: false
app:
  schedule: '*/10 * * * * ?'


---

spring:
  profiles: test
  profiles.include: docker_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
  liquibase:
    enabled: true
  main:
    banner-mode: "off"
app:
  schedule: '*/10 * * * * ?'



