version: '3'
services:
    squid:
        container_name: squid
        image: sameersbn/squid
        restart: always
        volumes:
            - /opt/squid/cache:/var/spool/squid
            - /opt/squid/logs:/var/log/squid
            - /opt/squid/conf:/etc/squid
        environment:
            SQUID_VERSION: 4.7
        ports:
            - "3128:3128"
    privoxy:
        container_name: privoxy
        image: vimagick/privoxy
        ports:
            - "8118:8118"
        volumes:
            - /opt/privoxy/conf/config:/etc/privoxy/config
            - /opt/privoxy/logs:/var/log/privoxy
        restart: always