worker_processes  1;

error_log /dev/stderr warn;

env JWT_SECRET;
env GATEWAY_URI;
env CLIENTID;
env CLIENT_SECRET;
env BASIC_AUTH;
env PROFILE;

events {
    worker_connections  1024;
}




http {
    default_type  application/octet-stream;

    resolver local=on;

    log_format main escape=json
    '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"remote_user":"$remote_user",'
    '"request":"$request",'
    '"status": "$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":"$request_time",'
    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent",'
    '"http_x_forwarded_for":"$http_x_forwarded_for"'
    '}';

     access_log /dev/stdout main;

      lua_package_path "/usr/local/openresty/lualib/?.lua;;";

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    #init_worker_by_lua_file /heartbeat.lua;


   init_worker_by_lua_block {
       os.execute('/init_eureka.sh')
       local delay = 10  -- in seconds
       local new_timer = ngx.timer.at
       local log = ngx.log
       local ERR = ngx.ERR
       local check

       check = function(premature)
           if not premature then
               -- do the health check or other routine work
               os.execute('/heartbeat_eureka.sh')
               local ok, err = new_timer(delay, check)
               if not ok then
                   log(ERR, "failed to create timer: ", err)
                   return
               end
           end
       end

       local hdl, err = new_timer(delay, check)
       if not hdl then
           log(ERR, "failed to create timer: ", err)
           return
       end
   }


    server {

	listen 80;

    client_max_body_size 256m;
    proxy_buffer_size   64m;
    proxy_buffers   8 64m;
    proxy_busy_buffers_size   64m;

      location / {

                 if ($request_method = 'OPTIONS') {
                  add_header Set-Cookie "COOKIE_BEARER=$arg_token;HttpOnly";
                  return 204;
                 }

          access_by_lua_file /bearer.lua;
          proxy_pass http://rep-viewer:15814/;
       }




    }


    include /etc/nginx/conf.d/*.conf;
}
