spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  kafka.consumer.properties.spring.json.trusted.packages: checkUnits
  cloud:
    stream:
      bindings:
        input:
          destination: exec_results
          group: analyzers
          consumer:
            concurrency: 10
            useNativeDecoding: true
        output.destination: results
        springCloudBusInput:
          destination: bus_config_input
          group: analyzer:${spring.cloud.client.ip-address}
        springCloudBusOutput.destination: bus_config_output
      kafka:
        binder:
          brokers:
            "kafka-0-as-15-8-dev.eclsoft.ru:9094,
            kafka-1-as-15-8-dev.eclsoft.ru:9094,
            kafka-2-as-15-8-dev.eclsoft.ru:9094"
          minPartitionCount: 12
          replicationFactor: 3
          configuration:
            max.request.size: 10485760
        bindings:
          input:
            consumer:
              ackEachRecord: true
              configuration:
                key.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                max.poll.records: 1
                max.poll.interval.ms: 120000
                auto.offset.reset: latest
          output:
            producer:
              configuration:
                max.request.size: 10485760
                retries: 10
                key.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          springCloudBusInput:
            consumer:
              resetOffsets: true
              startOffset: latest
gateway.url: "https://as-15-8-dev.eclsoft.ru/api"
source_path_vpn: /logs/content.txt
source_path_anonym: /logs/content.txt
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
  cloud.stream:
    kafka.binder:
      brokers: 10.97.220.178:9092,10.97.220.179:9092,10.97.220.180:9092
      minPartitionCount: 250
    bindings:
      input:
        consumer.concurrency: 10
source_path_vpn:
source_path_anonym:
eureka:
  instance:
    metadata-map:
      expectedAmount: 25

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
source_path_vpn:
source_path_anonym:
eureka:
  instance:
    metadata-map:
      expectedAmount: 5

---

spring:
  profiles: dev_ashabalin, dev_asavin, ifilimonov
  profiles.include: local_log
  cloud.stream:
    bindings:
      input:
        consumer:
          concurrency: 7
    kafka.bindings.jobs.consumer:
      configuration:
        max.poll.interval.ms: 300000
source_path_vpn:
source_path_anonym:

---

spring:
  profiles: dev_ashabalin
  cloud.stream:
    bindings:
      input.destination: exec_results_ashabalin
      output.destination: results_ashabalin
      springCloudBusInput.destination: bus_config_input_ashabalin
      springCloudBusOutput.destination: bus_config_output_ashabalin
---

spring:
  profiles: dev_asavin
  cloud.stream:
    bindings:
      input.destination: exec_results_asavin
      output.destination: results_asavin
      springCloudBusInput.destination: bus_config_input_asavin
      springCloudBusOutput.destination: bus_config_output_asavin