spring:
  main.allow-bean-definition-overriding: true
  kafka.consumer.properties.spring.json.trusted.packages: checkUnits
  cloud:
    stream:
      bindings:
        input:
          destination: exec_results
          group: analyzers
          consumer:
            concurrency: 4
            useNativeDecoding: true
        output.destination: analysis_results
        notifications.destination: job_notifications
        springCloudBusInput:
          destination: bus_config_input
          group: analyzer:${spring.cloud.client.ip-address}
        springCloudBusOutput.destination: bus_config_output
      kafka:
        binder:
          brokers: 172.16.6.122:9092,172.16.6.123:9092,172.16.6.124:9092
          minPartitionCount: 24
          configuration:
            max.request.size: 10485760
        bindings:
          input:
            consumer:
              concurrency: 1
              ackEachRecord: true
              configuration:
                key.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                max.poll.records: 1
                max.poll.interval.ms: 120000
          output:
            producer:
              configuration:
                max.request.size: 10485760
                key.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          notifications:
            producer.configuration:
              key.serializer: org.springframework.kafka.support.serializer.JsonSerializer
gateway.url: ${GATEWAY_URI:http://localhost:15880}
source_path_vpn: /logs/content.txt
source_path_anonym: /logs/content.txt

---

spring:
  profiles: prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
  cloud.stream:
    kafka.binder:
      brokers: 10.97.220.178:9092,10.97.220.179:9092,10.97.220.180:9092
      minPartitionCount: 250
    bindings:
      input:
        consumer.concurrency: 10
source_path_vpn:
source_path_anonym:
eureka:
  instance:
    metadata-map:
      expectedAmount: 25

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
source_path_vpn:
source_path_anonym:
eureka:
  instance:
    metadata-map:
      expectedAmount: 6

---

spring:
  profiles: dev_ashabalin, dev_asinyavin, dev_asavin, dev_pvorobiev, dev_danikanov
  profiles.include: local_log
  cloud.stream:
    bindings:
      input:
        consumer:
          concurrency: 7
    kafka.bindings.jobs.consumer:
      configuration:
        max.poll.interval.ms: 300000
source_path_vpn:
source_path_anonym:

---

spring:
  profiles: dev_ashabalin
  cloud.stream:
    bindings:
      input.destination: exec_results_ashabalin
      output.destination: analysis_results_ashabalin
      notifications.destination: job_notifications_ashabalin
      springCloudBusInput.destination: bus_config_input_ashabalin
      springCloudBusOutput.destination: bus_config_output_ashabalin

---


spring:
  profiles: dev_asinyavin
  cloud.stream:
    bindings:
      input.destination: exec_results_asinyavin
      output.destination: analysis_results_asinyavin
      notifications.destination: job_notifications_asinyavin
      springCloudBusInput.destination: bus_config_input_asinyavin
      springCloudBusOutput.destination: bus_config_output_asinyavin

---

spring:
  profiles: dev_asavin
  cloud.stream:
    bindings:
      input.destination: exec_results_asavin
      output.destination: analysis_results_asavin
      notifications.destination: job_notifications_asavin
      springCloudBusInput.destination: bus_config_input_asavin
      springCloudBusOutput.destination: bus_config_output_asavin

---

spring:
  profiles: dev_pvorobiev
  cloud.stream:
    bindings:
      input. destination: exec_results_pvorobiev
      output.destination: analysis_results_pvorobiev
      notifications.destination: job_notifications_pvorobiev
      springCloudBusInput.destination: bus_config_input_pvorobiev
      springCloudBusOutput.destination: bus_config_output_pvorobiev

---

spring:
  profiles: dev_danikanov
  cloud.stream:
    bindings:
      input.destination: exec_results_danikanov
      output.destination: analysis_results_danikanov
      notifications.destination: job_notifications_danikanov
      springCloudBusInput.destination: bus_config_input_danikanov
      springCloudBusOutput.destination: bus_config_output_danikanov