version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: dcr.ec-leasing.ru/as-15-8/elk/elasticsearch:7.2.0
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ~/as-15-8-smuf/elkb/elasticsearch/data:/usr/share/elasticsearch/data:rw
  logstash:
    container_name: logstash
    image: dcr.ec-leasing.ru/as-15-8/elk/logstash:7.2.0
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ~/as-15-8-smuf/elkb/logstash/pipeline:/usr/share/logstash/pipeline:ro
  kibana:
    container_name: kibana
    image: dcr.ec-leasing.ru/as-15-8/elk/kibana:7.2.0
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"