version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: harbor.ec-leasing.ru/as_15_8/elk/elasticsearch:7.2.0
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ~/as-15-8-smuf/elkb/elasticsearch/data:/usr/share/elasticsearch/data:rw
  logstash:
    container_name: logstash
    image: harbor.ec-leasing.ru/as_15_8/elk/logstash:7.2.0
    restart: on-failure
    depends_on:
      - elasticsearch
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ~/as-15-8-smuf/elkb/logstash/pipeline:/usr/share/logstash/pipeline:ro
  kibana:
    container_name: kibana
    image: harbor.ec-leasing.ru/as_15_8/elk/kibana:7.2.0
    restart: on-failure
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  curator:
    container_name: curator
    image: harbor.ec-leasing.ru/as_15_8/es_curator:5.4.0
    restart: on-failure
    depends_on:
      - elasticsearch
    environment:
      - "PERIOD=6hourly"
      - "KEEP_DAYS=3"
      - "INDEX_PREFIX=logstash"
    command: "--host elasticsearch --port 9200"
