input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
      add_field => {
          "container_name" => "%{[container][name]}"
          "container_image_name" => "%{[container][image][name]}"
          "docker_compose_project" => "%{[docker][container][labels][com_docker_compose_project]}"
          "docker_compose_service" => "%{[docker][container][labels][com_docker_compose_service]}"
          "hostname" => "%{[host][name]}"
      }
  }
  prune {
    whitelist_names => [
        "@timestamp",
        "^application\_",
        "^container\_",
        "^docker\_",
        "hostname",
        "level",
        "message",
        "stream",
        "thread",
        "timestamp",
        "exception"
    ]
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
  }
}