subsystem: SMUF
server:
  port: 8761
logging:
  config: config/logback-spring.xml
spring:
  application.name: discovery
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

---

spring:
  profiles: test, prod
  profiles.include: docker_log
  main:
    banner-mode: "off"

---

spring:
  profiles: dev_asavin, dev_ashabalin
  profiles.include: local_log
  main:
    banner-mode: "off"
