subsystem: SMUF
server:
  port: 8761
  tomcat:
    max-threads: 5000
logging:
  config: config/logback-spring.xml
spring:
  application.name: discovery
eureka:
  server:
    peer-node-total-connections: 5000
    peer-node-total-connections-per-host: 5000
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: false
    oauth2:
      clientId: discovery
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${AUTH_SERVER_URI:http://localhost:15805}/oauth/token
security:
  oauth2:
    resource:
      tokenInfoUri: ${AUTH_SERVER_URI:http://localhost:15805}/oauth/check_token
    client:
      clientId: discovery
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${gateway.url}/security/oauth/token

---

spring:
  profiles: test, prod
  profiles.include: docker_log
  main:
    banner-mode: "off"

---

spring:
  profiles: dev_asavin, dev_ashabalin
  profiles.include: local_log
  main:
    banner-mode: "off"
