http_port 3132
acl kasp_port localport 3132

cache_peer 10.97.220.159 parent 3128 0 round-robin no-query name=kas_159
cache_peer 10.97.220.246 parent 3128 0 round-robin no-query name=kas_246
cache_peer 10.97.220.247 parent 3128 0 round-robin no-query name=kas_247
cache_peer 10.97.220.248 parent 3128 0 round-robin no-query name=kas_248
cache_peer 10.97.220.249 parent 3128 0 round-robin no-query name=kas_249

cache_peer_access kas_159 allow kasp_port
cache_peer_access kas_159 deny_all
cache_peer_access kas_246 allow kasp_port
cache_peer_access kas_246 deny_all
cache_peer_access kas_247 allow kasp_port
cache_peer_access kas_247 deny_all
cache_peer_access kas_248 allow kasp_port
cache_peer_access kas_248 deny_all
cache_peer_access kas_249 allow kasp_port
cache_peer_access kas_249 deny_all