http_port 3128
acl torguard_port localport 3128

cache_peer nl.torguardvpnaccess.com parent 6060 0 no-query  login=m8kabanb2b376oi:4Kh4P768AC44NBh name=torguard_host

cache_peer_access torguard_host allow torguard_port
cache_peer_access torguard_host deny all