subsystem: PPO
server:
  port: 15813
logging:
  config: config/logback-spring.xml
gateway.url: ${GATEWAY_URI:http://localhost:15880}
eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${gateway.url}/eureka
    oauth2:
      clientId: report_generator
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${gateway.url}/security/oauth/token
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      subsystem: ${subsystem}
spring:
  application.name: report_generator
  main.allow-bean-definition-overriding: true
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    max-active: 5
    username: as_user
    password: as_user
security:
  oauth2:
    resource:
      jwk:
        keySetUri: ${gateway.url}/security/.well-known/jwks.json
    client:
      clientId: report_generator
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${gateway.url}/security/oauth/token

---

spring:
  profiles: prod
  profiles.include: docker_log
  datasource:
    url: jdbc:postgresql://10.97.220.144:5432/asdb
  main:
    banner-mode: "off"
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: test
  profiles.include: docker_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
  main:
    banner-mode: "off"
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: dev_asin
  profiles.include: local_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test