server:
    port: 15800
    tomcat:
        max-threads: 200
logging:
    config: config/logback-spring.xml
spring:
    application:
        name: as15-8-updater
    datasource:
        test-while-idle: true
        validation-query: SELECT 1;
        time-between-eviction-runs-millis: 300000
        username: as_user
        password: as_user
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                format_sql: true
        databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
    app:
        jwt:
            secret: Gk-Xun_Yrkd0zigpysWS
            ttl: 86400
        cors:
            origin: "*"
    rest_base_url: "http://bo.esoftproject.ru/register-vpn/api/as15-8"
---

spring:
    profiles: dev_pvorobiev
    jpa:
        hibernate:
            ddl-auto: none
    liquibase:
        enabled: true
        change-log: classpath:/data/changelog/db.changelog.master.xml
    datasource:
        url: jdbc:postgresql://192.168.5.195:5432/asdb_test

cron:
    expression:
        arrangement: "0 * * ? * *"

