url=jdbc:postgresql://192.168.5.211:5432/asdb
username=as_user
password=as_user
changeLogFile=data/db.changelog.master.xml

diffChangeLogFile=src/main/resources/data/changelog/dispatcher.0026.result_pk.xml

referenceUrl=hibernate:spring:model\
  ?dialect=org.hibernate.dialect.PostgreSQLDialect\
  &hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy\
  &hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

defaultSchemaName=results
changelogSchemaName=public

diffTypes=tables, columns, indexes, foreignkeys, primarykeys, uniqueconstraints