# suppress inspection "SpringBootApplicationProperties" for whole file
####### HTTP ##############
server.port=8090
spring.app.cors.origin=*
spring.app.jwt.secret=Gk-Xun_Yrkd0zigpysWS
####### DATASOURCE ##############
spring.datasource.url=jdbc:postgresql://osmdb:5432/db?currentSchema=sor
spring.datasource.username=api
spring.datasource.password=api
####### LOG LEVEL ##############
logging.level.org.springframework.security:info
logging.level.org.springframework.security.ldap:info
logging.level.org.springframework.ldap=info
