log4j.rootCategory=INFO, file

# Set to DEBUG to see a lot more messages from BIRT
log4j.logger.org.eclipse=INFO, engine
log4j.additivity.org.eclipse=false

log4j.logger.org.eclipse.birt=INFO, engine
log4j.additivity.org.eclipse.birt=false

log4j.logger.org.eclipse.birt.data=WARN, engine
log4j.additivity.org.eclipse.birt.data

log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=/reporting/log/birt/birt.log
log4j.appender.file.MaxFileSize=5000KB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=[%d{ISO8601}] %-5p [%t] J:%X{jobId} - (%F:%L) - %m%n

log4j.appender.engine=org.apache.log4j.RollingFileAppender
log4j.appender.engine.File=/reporting/log/birt/engine.log
log4j.appender.engine.MaxFileSize=2000KB
log4j.appender.engine.MaxBackupIndex=10
log4j.appender.engine.layout=org.apache.log4j.PatternLayout
log4j.appender.engine.layout.ConversionPattern=[%d{ISO8601}] %-5p [%t] J:%X{jobId} - %c - %m%n