server:
    port: 15800
    tomcat:
        max-threads: 200
spring:
    datasource:
        test-while-idle: true
        validation-query: SELECT 1;
        time-between-eviction-runs-millis: 300000
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                format_sql: true
        databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
    app:
        jwt:
            secret: Gk-Xun_Yrkd0zigpysWS
            ttl: 86400
        cors:
            origin: "*"
ldap:
    enabled: true
    domain: designdiv.ecleasing.ru
    urls: ldap://192.168.1.52:389/
    base:
        dn: OU=AS_15_8,DC=designdiv,DC=ecleasing,DC=ru
    user:
        dn:
            pattern: sAMAccountName={0}
    login:
        role: CN=ROLE_OPERATOR,OU=roles,OU=AS_15_8,DC=designdiv,DC=ecleasing,DC=ru
        filter: "(&(objectClass=user)(userPrincipalName={0})(memberof=${ldap.login.role}))"

---

spring:
    profiles: dev_asavin
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            javax:
                persistence:
                    schema-generation:
                         create-source: metadata
                         scripts:
                              action: drop-and-create
                              create-target: scripts/create.sql
                              drop-target: scripts/drop.sql
            hibernate:
                hbm2ddl:
                    delimiter: ";"
db:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.5.195:5432/asdb-test
    username: as_user
    password: as_user
---

spring:
    profiles: test
    jpa:
        hibernate:
            ddl-auto: none
db:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.5.195:5432/asdb
    username: as_user
    password: as_user
    