spring:
  main.allow-bean-definition-overriding: true
  kafka.streams.properties.spring.json:
    trusted.packages: checkUnits
  cloud:
    stream:
      bindings:
        inputResults:
          destination: results
          contentType: application/json
          nativeDecoding: true
        results_table:
          destination: results_table
        screenshots_table:
          destination: screenshots_table
        results_count_table:
          destination: results_count_table
        outputStopArrangementEvents:
          destination: bus_config_input
        springCloudBusInput:
          destination: bus_config_input
          group: dispatcher:${spring.cloud.client.ip-address}
        springCloudBusOutput.destination: bus_config_output
      kafka:
        binder:
          brokers: 192.168.5.12:9094,192.168.5.33:9094,192.168.5.184:9094
          minPartitionCount: 24
        streams:
          binder:
            brokers: 192.168.5.12:9094,192.168.5.33:9094,192.168.5.184:9094
            minPartitionCount: 24
            configuration:
              default:
                key.serde: org.springframework.kafka.support.serializer.JsonSerde
                value.serde: org.springframework.kafka.support.serializer.JsonSerde
              spring.json:
                key.default.type: checkUnits.CheckUnitKey
                value.default.type: analysis.CheckUnitResult
              windowstore.changelog.additional.retention.ms: -1
              commit.interval.ms: 1000
              max.request.size: 10485760
              max.partition.fetch.bytes: 10485760
              max.poll.records: 100
              max.poll.interval.ms: 600000
          bindings:
            inputResults:
              consumer:
                application-id: dispatchers
                useNativeDecoding: true
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    max-active: 5
    username: as_user
    password: as_user
  liquibase:
    enabled: true
    change-log: classpath:/data/db.changelog.master.xml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
results.save.schedule: '0 */1 * * * ?'

---

spring:
  profiles: prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://10.97.220.144:5432/asdb
  cloud:
    stream:
      bindings:
        inputResults:
          consumer:
            concurrency: 25
      kafka:
        binder:
          brokers: 10.97.220.178:9092,10.97.220.179:9092,10.97.220.180:9092
          minPartitionCount: 250
        streams.binder:
          brokers: 10.97.220.178:9092,10.97.220.179:9092,10.97.220.180:9092
          minPartitionCount: 250
          configuration:
            num.stream.threads: 10
            replication.factor: 3
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: dev_ashabalin, dev_asin, dev_asavin, dev_pvorobiev, dev_danikanov
  profiles.include: local_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
  liquibase:
    enabled: false

---

spring:
  profiles: dev_ashabalin
  cloud:
    stream:
      bindings:
        inputResults.destination: results_ashabalin
        springCloudBusInput.destination: bus_config_input_ashabalin
        springCloudBusOutput.destination: bus_config_output_ashabalin
  datasource:
    url: jdbc:postgresql://192.168.5.211:5432/asdb_test
  liquibase:
    enabled: true
    change-log: classpath:/data/db.changelog.master.xml

---

logging:
  config:
  level:
    root: info
spring:
  profiles: dev_asin
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
  cloud:
    stream:
      bindings:
        inputResults.destination: results_asin
        springCloudBusInput.destination: bus_config_input_asin
        springCloudBusOutput.destination: bus_config_output_asin

---

spring:
  profiles: dev_asavin
  cloud:
    stream:
      bindings:
        inputResults.destination: results_asavin
        springCloudBusInput.destination: bus_config_input_asavin
        springCloudBusOutput.destination: bus_config_output_asavin
  datasource:
    url: jdbc:postgresql://192.168.5.211:5432/asdb_test2

---

spring:
  profiles: dev_pvorobiev
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
  cloud:
    stream:
      bindings:
        inputResults.destination: results_pvorobiev
        springCloudBusInput.destination: bus_config_input_pvorobiev
        springCloudBusOutput.destination: bus_config_output_pvorobiev

---

spring:
  profiles: dev_danikanov
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
  cloud:
    stream:
      bindings:
        inputResults.destination: results_danikanov
        springCloudBusInput.destination: bus_config_input_danikanov
        springCloudBusOutput.destination: bus_config_output_danikanov