logging.level.root: INFO
logging.level.org.springframework.http: DEBUG
gateway.url: ${GATEWAY_URI:http://localhost:15880}
config.url:  ${gateway.url}/config
rep_scheduler.url:  ${gateway.url}/report_scheduler
act:
  screenshotes.max-count: 10
spring:
  main.allow-bean-definition-overriding: true
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    username: as_user
    password: as_user
  liquibase:
    enabled: true
    change-log: classpath:/data/db.changelog.master.xml
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  app:
    schedule:
#      missions: '0 0 0 * * ?'
      missions: '0 */1 * * * ?'
    jwt:
      secret: Gk-Xun_Yrkd0zigpysWS
      ttl: 86400
    cors:
      origin: "*"
  rest_base_url: "http://bo.esoftproject.ru/register-vpn/api/as15-8"
registry-anonymizers:
  proxy-ip: "212.83.9.108"
  proxy-port: 3128
  username: test158
  password: test158
cron:
  expression:
    arrangement: "0 * * ? * *"

---

spring:
  profiles: prod
  profiles.include: docker_log
  app:
    schedule:
      missions: '0 0 0 * * ?'
#      missions: '0 */1 * * * ?'
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://10.97.220.144:5432/asdb
#  rest_base_url: "https://arm-r.rkn.gov.ru/register-vpn/api/as15-8"
registry-anonymizers:
  proxy-ip: ""
  proxy-port: 3128
#  username: As158
#  password: reEO964YnhOE

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
registry-anonymizers:
  proxy-ip: ""

---

spring:
  profiles: dev_pvorobiev, dev_asavin, dev_ashabalin, dev_jspirina
  profiles.include: local_log
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
eureka.client.enabled: true

---

spring:
  profiles: dev_asavin
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test2
  liquibase:
    enabled: true
  app:
    schedule:
      missions: '0 0 0 * * ?'

---

logging:
  config:
  level:
    root: info
    org.springframework.http: debug
spring:
  profiles: dev_asin
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
    change-log: classpath:/data/db.changelog.master.xml
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
eureka.client.enabled: true