logging.level.root: INFO
spring:
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    username: as_user
    password: as_user
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  app:
    jwt:
      secret: Gk-Xun_Yrkd0zigpysWS
      ttl: 86400
    cors:
      origin: "*"
  rest_base_url: "http://bo.esoftproject.ru/register-vpn/api/as15-8"
registry-anonymizers:
  proxy-ip: "212.83.9.108"
  proxy-port: 3128
  username: test158
  password: test158
cron:
  expression:
    arrangement: "0 * * ? * *"

---

eureka:
  client.enabled: false
spring:
  profiles: prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/data/changelog/db.changelog.master.xml
  datasource:
    url: jdbc:postgresql://10.97.220.144:5432/asdb
  rest_base_url: "https://arm-r.rkn.gov.ru/register-vpn/api/as15-8"
registry-anonymizers:
  proxy-ip: ""
  proxy-port: 3128
  username: As158
  password: reEO964YnhOE

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/data/changelog/db.changelog.master.xml
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
registry-anonymizers:
  proxy-ip: ""

---

spring:
  profiles: dev_pvorobiev, dev_asavin, dev_ashabalin, dev_jspirina
  profiles.include: local_log
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/data/changelog/db.changelog.master.xml
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
eureka.client.enabled: false