server:
  port: 15880
logging:
  config: config/logback-spring.xml
spring:
  application.name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
  debug.request: true
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

---

spring:
  profiles: prod
zuul:
  routes:
    pod:
      path: /pod/**
      url: http://10.97.220.146:15801
    config:
      path: /config/**
      url: http://10.97.220.145:15802
    ppm:
      path: /**
      url: http://10.97.220.145:15800

---

spring:
  profiles: test
zuul:
  routes:
    pod:
      path: /pod/**
      url: http://192.168.5.210:15801
    config:
      path: /config/**
      url: http://192.168.5.253:15802
    ppm:
      path: /**
      url: http://192.168.5.253:15800

---

spring:
  profiles: dev_ashabalin, dev_asavin, dev_pvorobiev, dev_jspirina, dev_asinyavin
zuul:
  routes:
    pod:
      path: /pod/**
      url: http://localhost:15801
    config:
      path: /config/**
      url: http://localhost:15802
    ppm:
      path: /**
      url: http://localhost:15800