server:
  port: 15880
logging:
  config: config/logback-spring.xml
spring:
  application.name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
zuul:
  debug.request: true
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 120000
  routes:
    pod:
      path: /pod/**
      serviceId: pod
    config:
      path: /config/**
      serviceId: config_server
    ppm:
      path: /**
      serviceId: ppm

---

spring:
  profiles: dev_pvorobiev, dev_asavin, dev_ashabalin, dev_jspirina
eureka.client.enabled: false