subsystem: PPO
server:
  port: 15814
  servlet:
    context-path: /viewer
logging:
  config: config/logback-spring.xml
gateway.url: ${GATEWAY_URI:http://localhost:15880}
#eureka:
#  client:
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: ${gateway.url}/eureka
#    oauth2:
#      clientId: birt-viewer
#      clientSecret: 1q0p2w9o
#      grantType: client_credentials
#      accessTokenUri: ${gateway.url}/security/oauth/token
#  instance:
#    preferIpAddress: true
#    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring:
  application.name: birt-viewer
  main.allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:data/db.changelog.master.xml
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    max-active: 5
    username: ${DATABASE_USR:as_user}
    password: ${DATABASE_PWD:as_user}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
security:
  oauth2:
    resource:
      tokenInfoUri: ${gateway.url}/security/oauth/check_token
    client:
      clientId: birt-viewer
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${gateway.url}/security/oauth/token

---

spring:
  profiles: prod
  profiles.include: docker_log
  datasource:
    url: jdbc:postgresql://10.97.220.144:5432/asdb?stringtype=unspecified
  liquibase:
    enabled: true
  main:
    banner-mode: "off"
app:
  schedule: '*/10 * * * * ?'

---

spring:
  profiles: test
  profiles.include: docker_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_release?stringtype=unspecified
  liquibase:
    enabled: true
  main:
    banner-mode: "off"
app:
  schedule: '*/10 * * * * ?'

---

logging:
  config:
  level:
    root: info
    model: debug
    repositories: debug
    controllers: debug
    common: debug
    schedule: debug
#    org.springframework.data: debug
#    org.springframework.web: debug
#    org.springframework.http: debug
#    org.hibernate.SQL: debug
spring:
  profiles: dev_asin
  profiles.include: local_log
  datasource:
    url: ${DATABASE_URI:jdbc:postgresql://192.168.5.195:5432/asdb_test?stringtype=unspecified}
  liquibase:
    enabled: false
app:
  schedule: '*/10 * * * * ?'