subsystem: SMUF
server:
  port: 15880
logging:
  config: config/logback-spring.xml
spring:
  application.name: gateway
  main.allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
    oauth2:
      clientId: gateway
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri:  ${AUTH_SERVER_URI:http://localhost:15805}/oauth/token
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
security:
  basic.enabled: false
  oauth2:
    resource:
      tokenInfoUri: http://${spring.cloud.client.ip-address}:${server.port}/security/oauth/check_token
    client:
      clientId: gateway
      clientSecret: 1q0p2w9o
zuul:
  debug.request: true
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 120000
  routes:
    eureka:
      path: /eureka/**
      serviceId: discovery
      stripPrefix: false
    pod:
      path: /pod/**
      serviceId: pod
    config:
      path: /config/**
      serviceId: config_server
    ppm:
      path: /ppm/**
      serviceId: ppm
    ppt:
      path: /**
      serviceId: ppt
    security:
      path: /security/**
      serviceId: auth_server
    report_scheduler:
      path: /report_scheduler/**
      serviceId: report_scheduler
    report_generator:
      path: /report_generator/**
      serviceId: report_generator
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000
  eureka:
    enabled: true

---

spring:
  profiles: test, prod
  profiles.include: docker_log
  main:
    banner-mode: "off"

---

spring:
  profiles: dev_pvorobiev, dev_asavin, dev_ashabalin, dev_asinyavin, dev_jspirina, dev_asin
  profiles.include: local_log