subsystem: SMUF
server:
  port: 15880
logging:
  config: config/logback-spring.xml
spring:
  application.name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
zuul:
  debug.request: true
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 120000
  routes:
    eureka:
      path: /eureka/**
      serviceId: discovery
      stripPrefix: false
    pod:
      path: /pod/**
      serviceId: pod
    config:
      path: /config/**
      serviceId: config_server
    ppm:
      path: /**
      serviceId: ppt
    oauth:
      path: /oauth/**
      stripPrefix: false
      serviceId: authentication_service
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000
  eureka:
    enabled: true
security:
  oauth2:
    resource:
      jwt:
        key-value: as-15-8

---

spring:
  profiles: test, prod
  profiles.include: docker_log
  main:
    banner-mode: "off"

---

spring:
  profiles: dev_pvorobiev, dev_asavin, dev_ashabalin, dev_asinyavin, dev_jspirina
  profiles.include: local_log