subsystem: SMUF
server:
  port: 15880
  tomcat:
    max-threads: 5000
logging:
  config: config/logback-spring.xml
spring:
  application.name: gateway
  main.allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
    oauth2:
      clientId: gateway
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri:  ${AUTH_SERVER_URI:http://localhost:15805}/oauth/token
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      subsystem: ${subsystem}
security:
  basic.enabled: false
  oauth2:
    resource:
      tokenInfoUri: http://${spring.cloud.client.ip-address}:${server.port}/security/oauth/check_token
    client:
      clientId: gateway
      clientSecret: 1q0p2w9o
zuul:
  semaphore.maxSemaphores: 1000000
  debug.request: true
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis: 5000
    max-per-route-connections: 5000
    max-total-connections: 5000
  routes:
    eureka:
      path: /eureka/**
      serviceId: discovery
      stripPrefix: false
    kibana:
      path: /kibana/**
      url: http://${spring.cloud.client.ip-address}:5601
    pod:
      path: /pod/**
      serviceId: pod
    config:
      path: /config/**
      serviceId: config_server
    ppm:
      path: /ppm/**
      serviceId: ppm
    dispatcher:
      path: /dispatcher/**
      serviceId: dispatcher
    ppt:
      path: /**
      serviceId: ppt
    security:
      path: /security/**
      serviceId: auth_server
    ppo:
      path: /ppo/**
      serviceId: report_scheduler
    viewer:
      path: /viewer/**
      serviceId: birt-viewer
      stripPrefix: false
    report_generator:
      path: /report_generator/**
      serviceId: report_generator
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000
  SocketTimeout: 120000
  eureka:
    enabled: true

---

spring:
  profiles: test, prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: dev_pvorobiev, dev_asavin, dev_ashabalin, dev_asinyavin, dev_danikanov
  profiles.include: local_log

---

logging:
  config:
  level:
    root: info
spring:
  profiles: dev_asin
  profiles.include: local_log