version: '3.7'
networks:
  as-15-8-net:
    name: "host"
    external: true
services:
  dispatcher:
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-dispatcher:latest
    networks:
      - as-15-8-net
    deploy:
      placement:
        constraints:
          - node.hostname == as158-pmk
      mode: replicated
      replicas: 1
    environment:
      PROFILE: test
      GATEWAY_URI: http://192.168.5.50:15880
      TZ: "Europe/Moscow"
    ports:
      - target: 11300
        published: 11300
        protocol: tcp
        mode: host
    volumes:
      - ~/as-15-8-pmk/dispatcher/logs:/log
      - ~/as-15-8-pmk/dispatcher/kafka-streams:/var/lib/kafka-streams:ro
    configs:
      - source: dispatcher-bootstrap
        target: /config/bootstrap.yml
      - source: dispatcher-config
        target: /config/application.yml
      - source: dispatcher-logback
        target: /config/logback-spring.xml
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  executor:
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-executor:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname != as158-pmk
    networks:
      - as-15-8-net
    stop_grace_period: 5m
    environment:
      PROFILE: test
      GATEWAY_URI: http://192.168.5.50:15880
      TZ: "Europe/Moscow"
    ports:
      - target: 11100
        published: 11100
        protocol: tcp
        mode: host
    volumes:
      - ~/as-15-8-pmk/executor/logs:/log
    configs:
      - source: executor-bootstrap
        target: /config/bootstrap.yml
      - source: executor-config
        target: /config/application.yml
      - source: executor-logback
        target: /config/logback-spring.xml
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  analyzer:
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-analyzer:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname != as158-pmk
    networks:
      - as-15-8-net
    environment:
      PROFILE: test
      GATEWAY_URI: http://192.168.5.50:15880
      TZ: "Europe/Moscow"
    ports:
      - target: 11200
        published: 11200
        protocol: tcp
        mode: host
    volumes:
      - ~/as-15-8-pmk/analyzer/logs:/log
    configs:
      - source: analyzer-bootstrap
        target: /config/bootstrap.yml
      - source: analyzer-config
        target: /config/application.yml
      - source: analyzer-logback
        target: /config/logback-spring.xml
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  filebeat:
    image: harbor.ec-leasing.ru/as_15_8/elk/filebeat:7.2.0
    deploy:
      mode: global
    networks:
      - as-15-8-net
    ports:
      - target: 58568
        published: 58568
        protocol: tcp
        mode: host
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/data:/usr/share/filebeat/data:rw
    command: filebeat -e -strict.perms=false
    user: root
    configs:
      - source: filebeat-config
        target: /usr/share/filebeat/filebeat.yml
configs:
  dispatcher-bootstrap:
    file: dispatcher/config/bootstrap.yml
  dispatcher-config:
    file: dispatcher/config/application.yml
  dispatcher-logback:
    file: dispatcher/config/logback-spring.xml
  executor-bootstrap:
    file: executor/config/bootstrap.yml
  executor-config:
    file: executor/config/application.yml
  executor-logback:
    file: executor/config/logback-spring.xml
  analyzer-bootstrap:
    file: analyzer/config/bootstrap.yml
  analyzer-config:
    file: analyzer/config/application.yml
  analyzer-logback:
    file: analyzer/config/logback-spring.xml
  filebeat-config:
    file: filebeat/filebeat.yml