subsystem: SMUF
server:
  port: 15802
gateway.url: ${GATEWAY_URI:http://localhost:15880}
logging:
  config: config/logback-spring.xml
eureka:
  client:
    serviceUrl:
      defaultZone: ${gateway.url}/eureka
    oauth2:
      clientId: config-server
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${gateway.url}/security/oauth/token
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
security:
  oauth2:
    resource:
      tokenInfoUri: ${gateway.url}/security/oauth/check_token
    client:
      clientId: config-server
      clientSecret: 1q0p2w9o
      grantType: client_credentials
      accessTokenUri: ${gateway.url}/security/oauth/token
spring:
  application.name: config_server
  profiles.include: jdbc
  main.allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog.master.xml
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    max-active: 5
    username: as_user
    password: as_user
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  cloud:
    bus.trace.enabled: true
    config:
      bus:
        enabled: true
      server.jdbc:
        sql: SELECT key, value from config.config where application=? and profile=? and label=?
        order: 1
        default-profile: test
        default-label: latest
    stream:
      bindings:
        springCloudBusInput:
          group: config_server
      kafka.binder:
        brokers: 192.168.5.12:9094,192.168.5.184:9094,192.168.5.211:9094
management.endpoints.web.exposure.include: bus-refresh

---

spring:
  profiles: prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://10.97.220.144:5432/asdb
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: bus_config_output
        springCloudBusOutput:
          destination: bus_config_input

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: bus_config_output
        springCloudBusOutput:
          destination: bus_config_input

---

logging:
  config:
  level:
    root: info
spring:
  profiles: dev_asin
  profiles.include: local_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
  liquibase:
    enabled: false
  cloud:
    bus.trace.enabled: false
    config:
      bus:
        enabled: false
    stream:
      bindings:
        springCloudBusInput:
          group: config_server
      kafka.binder:
        brokers:

---

spring:
  profiles: dev_pvorobiev, dev_asavin, dev_ashabalin, dev_jspirina
  profiles.include: local_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
  liquibase:
    enabled: false
    change-log: classpath:/db/db.changelog.master.xml
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: bus_config_output_ashabalin
        springCloudBusOutput:
          destination: bus_config_input_ashabalin