version: '3.7'
services:
  discovery:
    container_name: discovery
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-discovery
    restart: always
    network_mode: "host"
    volumes:
      - ~/as-15-8-smuf/discovery/logs:/log
      - ~/as-15-8-smuf/discovery/config:/config
    environment:
      PROFILE: test
      TZ: "Europe/Moscow"
    ports:
      - "8761:8761"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  gateway:
    container_name: gateway
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-gateway
    restart: always
    network_mode: "host"
    depends_on:
      - discovery
    volumes:
      - ~/as-15-8-smuf/gateway/logs:/log
      - ~/as-15-8-smuf/gateway/config:/config
    environment:
      PROFILE: test
      EUREKA_URI: http://192.168.5.50:8761
      AUTH_SERVER_URI: http://192.168.5.70:15805
      TZ: "Europe/Moscow"
    ports:
      - "15880:15880"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  config-server:
    container_name: config-server
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-config-server
    restart: always
    network_mode: "host"
    depends_on:
      - discovery
      - gateway
    volumes:
      - ~/as-15-8-smuf/config-server/logs:/log
      - ~/as-15-8-smuf/config-server/config:/config
    environment:
      PROFILE: test
      GATEWAY_URI: http://192.168.5.50:15880
      TZ: "Europe/Moscow"
    ports:
      - "15802:15802"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  filebeat:
    container_name: filebeat
    image: harbor.ec-leasing.ru/as_15_8/elk/filebeat:7.2.0
    restart: on-failure
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/data:/usr/share/filebeat/data:rw
    command: filebeat -e -strict.perms=false
    user: root
