version: '3.7'
services:
    squid:
        container_name: squid
        image: dcr.ec-leasing.ru/as-15-8/squid:3.5.27-1
        restart: always
        volumes:
            - /opt/squid/cache:/var/spool/squid
            - /opt/squid/logs:/var/log/squid
            - /opt/squid/conf:/etc/squid
        environment:
            SQUID_VERSION: 4.7
        ports:
            - "3128:3128"