subsystem: PPT
server:
  port: 15800
  tomcat:
    max-threads: 200
gateway.url: ${GATEWAY_URI:http://localhost:15880}
eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${gateway.url}/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring:
  application.name: ppt
  main.allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog.master.xml
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    username: as_user
    password: as_user
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect

---

spring:
  profiles: prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://10.97.220.144:5432/asdb
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: dev_asavin, dev_ashabalin, dev_pvorobiev, dev_danikanov, dev_msnopok
  profiles.include: local_log
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test

---

spring:
  profiles: dev_asavin
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb

---

spring:
  profiles: dev_ashabalin
  datasource:
    url: jdbc:postgresql://192.168.5.211:5432/asdb_test

---

spring:
  profiles: dev_pvorobiev
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test

---

spring:
  profiles: dev_danikanov
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb

---

spring:
  profiles: dev_msnopok
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
---

logging:
  config:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: info
spring:
  profiles: dev_asin
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test
