version: '3.2'
services:
    executor:
        image: harbor.ec-leasing.ru/as_15_8/as-15-8-executor:latest
        deploy:
            mode: global
        environment:
            PROFILE: test
        volumes:
            - ~/as-15-8-modules/executor-module/logs:/log
    analyzer:
        image: harbor.ec-leasing.ru/as_15_8/as-15-8-analyzer:latest
        deploy:
            mode: global
        environment:
            PROFILE: test
        volumes:
            - ~/as-15-8-modules/analyzer-module/logs:/log