version: '3'
services:
    as-15-8-rest:
        container_name: as-15-8_REST
        image: harbor.ec-leasing.ru/as_15_8/as-15-8-rest
        restart: always
        volumes:
            - ~/as-15-8-rest/logs:/log
        environment:
            PROFILE: test
            TZ: "Europe/Moscow"
        ports:
            - "15800:15800"