version: '3.2'
networks:
  as-15-8-net:
    external: true
services:
  dispatcher:
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-dispatcher:latest
    networks:
      - as-15-8-net
    environment:
      PROFILE: prod
      TZ: "Europe/Moscow"
    volumes:
      - ~/as-15-8-modules/dispatcher-module/logs:/log
  executor:
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-executor:latest
    deploy:
      mode: global
    networks:
      - as-15-8-net
    environment:
      PROFILE: prod
      TZ: "Europe/Moscow"
    volumes:
      - ~/as-15-8-modules/executor-module/logs:/log
  analyzer:
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-analyzer:latest
    deploy:
      mode: global
    networks:
      - as-15-8-net
    environment:
      PROFILE: prod
      TZ: "Europe/Moscow"
    volumes:
      - ~/as-15-8-modules/analyzer-module/logs:/log