version: '3.2'
services:
    executor:
        image: as-15-8-executor
        deploy:
            mode: global
        environment:
            PROFILE: test
        volumes:
            - ~/as_15_8_modules/executor-module/logs:/log
    analyzer:
        image: as-15-8-analyzer
        deploy:
            mode: global
        environment:
            PROFILE: test
        volumes:
            - ~/as_15_8_modules/analyzer-module/logs:/log