version: '3.7'
services:
  as-15-8-rest:
    container_name: as-15-8_REST
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-rest
    restart: always
    volumes:
      - ~/as-15-8-ppm/rest/logs:/log
      - ~/as-15-8-ppm/rest/config:/config
    environment:
      PROFILE: test
      TZ: "Europe/Moscow"
    ports:
      - "15800:15800"
  as-15-8-config-server:
    container_name: as-15-8_config-server
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-config-server
    restart: always
    volumes:
      - ~/as-15-8-ppm/config-server/logs:/log
      - ~/as-15-8-ppm/config-server/config:/config
    environment:
      PROFILE: test
      TZ: "Europe/Moscow"
    ports:
      - "15802:15802"
  as-15-8-gateway:
    container_name: as-15-8_gateway
    image: harbor.ec-leasing.ru/as_15_8/as-15-8-gateway
    restart: always
    volumes:
      - ~/as-15-8-ppm/gateway/logs:/log
      - ~/as-15-8-ppm/gateway/config:/config
    environment:
      PROFILE: test
      TZ: "Europe/Moscow"
    ports:
      - "15880:80"