selenium-hub-url: http://user:1q0p2w9o@192.168.5.75:4445/wd/hub
spring:
  main.allow-bean-definition-overriding: true
  kafka.consumer.properties.spring.json.trusted.packages: checkUnits
  cloud:
    stream:
      bindings:
        jobs:
          destination: jobs
          group: executors
          consumer:
            concurrency: 6
            useNativeDecoding: true
        executionResults.destination: exec_results
        results.destination: results
        springCloudBusInput:
          destination: bus_config_input
          group: executor:${spring.cloud.client.ip-address}
        springCloudBusOutput.destination: bus_config_output
        arrangementEvents:
          destination: arrangement_events
          group: executor:${spring.cloud.client.ip-address}
      kafka:
        binder:
          brokers: 192.168.5.12:9094,192.168.5.33:9094,192.168.5.184:9094
          minPartitionCount: 30
          replicationFactor: 3
          configuration:
            max.request.size: 10485760
        bindings:
          jobs:
            consumer:
              ackEachRecord: true
              configuration:
                key.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                max.poll.records: 1
                max.poll.interval.ms: 300000
                auto.offset.reset: latest
          executionResults:
            producer.configuration:
              key.serializer: org.springframework.kafka.support.serializer.JsonSerializer
          results:
            producer.configuration:
              key.serializer: org.springframework.kafka.support.serializer.JsonSerializer

---

spring:
  profiles: prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
  cloud.stream:
    kafka.binder:
      brokers: 10.97.220.178:9092,10.97.220.179:9092,10.97.220.180:9092
      minPartitionCount: 250
    bindings:
      jobs:
        consumer.concurrency: 10
selenium-hub-url: http://10.97.220.226:15800/wd/hub
eureka:
  instance:
    metadata-map:
      expectedAmount: 25

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
eureka:
  instance:
    metadata-map:
      expectedAmount: 5

---

spring:
  profiles: dev_ashabalin, dev_asin, dev_asavin, dev_pvorobiev, dev_danikanov
  profiles.include: local_log
  cloud:
    stream:
      bindings:
        jobs:
          consumer.concurrency: 7
      kafka.bindings.jobs.consumer:
        configuration:
          max.poll.interval.ms: 300000

---

spring:
  profiles: dev_ashabalin
  cloud:
    stream:
      bindings:
        jobs.destination: jobs_ashabalin
        executionResults.destination: exec_results_ashabalin
        results.destination: results_ashabalin
        springCloudBusInput.destination: bus_config_input_ashabalin
        springCloudBusOutput.destination: bus_config_output_ashabalin
nmap.path: C:\Program Files (x86)\Nmap

---

spring:
  profiles: dev_asin
  liquibase:
    enabled: false
  cloud.stream:
    bindings:
      jobs.destination: jobs_asinyavin
      executionResults.destination: exec_results_asinyavin
      results.destination: results_asinjavin
      springCloudBusInput.destination: bus_config_input_asinyavin
      springCloudBusOutput.destination: bus_config_output_asinyavin

---

spring:
  profiles: dev_asavin
  cloud.stream:
    bindings:
      jobs.destination: jobs_asavin
      executionResults.destination: exec_results_asavin
      results.destination: results_asavin
      springCloudBusInput.destination: bus_config_input_asavin
      springCloudBusOutput.destination: bus_config_output_asavin

---

spring:
  profiles: dev_pvorobiev
  cloud.stream:
    bindings:
      jobs.destination: jobs_pvorobiev
      executionResults.destination: exec_results_pvorobiev
      results.destination: results_pvorobiev
      springCloudBusInput.destination: bus_config_input_pvorobiev
      springCloudBusOutput.destination: bus_config_output_pvorobiev

---

spring:
  profiles: dev_danikanov
  cloud:
    stream:
      bindings:
        jobs.destination: jobs_danikanov
        executionResults.destination: exec_results_danikanov
        results.destination: results_danikanov
        springCloudBusInput.destination: bus_config_input_danikanov
        springCloudBusOutput.destination: bus_config_output_danikanov
eureka.client.enabled: false