version: '3.7'
services:
  haproxy:
    container_name: haproxy
    image: dcr.ec-leasing.ru/as-15-8/haproxy:2.1.2
    restart: always
    volumes:
      - /opt/haproxy/conf:/usr/local/etc/haproxy
    network_mode: "host"
    command: ["-f", "/usr/local/etc/haproxy"]