version: '3.7'
services:
  ppt:
    container_name: ppt
    image: dcr.ec-leasing.ru/as-15-8/as-15-8-ppt
    restart: always
    network_mode: "host"
    volumes:
      - ~/as-15-8-ppt/logs:/log
      - ~/as-15-8-ppt/config:/config
    environment:
      PROFILE: prod
      GATEWAY_URI: http://10.97.220.134:15880
      TZ: "Europe/Moscow"
    ports:
      - "15800:15800"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  filebeat:
    container_name: filebeat_ppt
    image: dcr.ec-leasing.ru/as-15-8/elk/filebeat:7.2.0
    restart: on-failure
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/data:/usr/share/filebeat/data:rw
    command: filebeat -e -strict.perms=false
    user: root