subsystem: SOIB
logging:
  config: config/logback-spring.xml
ldap:
  enabled: true
  domain: designdiv.ecleasing.ru
  source:
    url: ldap://192.168.1.52:389/
    base: OU=AS_15_8,DC=designdiv,DC=ecleasing,DC=ru
    roles-ou: OU=roles
    userDn: sa
    password: 12345
    pooled: true
management:
  health:
    ldap:
      enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog.master.xml
  datasource:
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 300000
    max-active: 5
    username: as_user
    password: as_user
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect

---

spring:
  profiles: prod
  profiles.include: docker_log
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://10.97.220.144:5432/asdb
ldap:
  domain: as158.ru
  source:
    url: ldap://10.97.220.140:389/
    base: OU=AS_15_8,DC=as158,DC=ru
    userDn: sa
    password: 1qaz@WSXQwerty123
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: test
  profiles.include: docker_log
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
eureka:
  instance:
    metadata-map:
      expectedAmount: 1

---

spring:
  profiles: dev_pvorobiev, dev_asavin, dev_ashabalin, dev_danikanov, dev_msnopok
  profiles.include: local_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test

---

spring:
  profiles: dev_pvorobiev
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test

---

spring:
  profiles: dev_asavin
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb

---

spring:
  profiles: dev_ashabalin
  datasource:
    url: jdbc:postgresql://192.168.5.211:5432/asdb_test

---


spring:
  profiles: dev_danikanov
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb

---


spring:
  profiles: dev_msnopok
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb
---

logging:
  config:
  level:
    root: info
spring:
  profiles: dev_asin
#  profiles.include: local_log
  datasource:
    url: jdbc:postgresql://192.168.5.195:5432/asdb_test