visible_hostname kas_01

http_port 3128

cache deny all

acl localnet src 10.97.220.0/24
acl localnet src fc00::/7
acl localnet src fe80::/10

http_access allow localnet
http_access deny all

server_persistent_connections off

forward_timeout 10 seconds

dns_nameservers 8.8.8.8 208.67.222.222
tcp_outgoing_address 10.102.37.150

header_access Host allow all
always_direct allow all