server:
    port: 11200
spring:
    kafka:
        bootstrap-servers: 192.168.5.12:9094,192.168.5.184:9094,192.168.5.211:9094
        group: analyzers
        auto-offset-reset: earliest

---

spring:
    profiles: test
    kafka:
        consume-topic: exec_results
        produce-topic: analysis_results

---

spring:
    profiles: dev_ashabalin
    kafka:
        consume-topic: exec_results_ashabalin
        produce-topic: analysis_results_ashabalin

---

spring:
    profiles: dev_asavin
    kafka:
        consume-topic: exec_results_asavin
        produce-topic: analysis_results_asavin

---

spring:
    profiles: dev_pvorobiev
    kafka:
        consume-topic: exec_results_pvorobiev
        produce-topic: analysis_results_pvorobiev

---

spring:
    profiles: dev_jspirina
    kafka:
        consume-topic: exec_results_jspirina
        produce-topic: analysis_results_jspirina